// Omarchy-style Quickshell bar for Hyprland.
//
// Mirrors the feel of Omarchy's default bar (config/omarchy/shell.json): one
// panel per screen, workspaces on the left, a centered clock, and status on the
// right. It is deliberately self-contained (no Omarchy scripts) and small
// enough to stay readable; add widgets as needed.
import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import Quickshell.Hyprland
import Quickshell.Bluetooth
import Quickshell.Networking
import Quickshell.Services.UPower
import Quickshell.Services.Pipewire
import Quickshell.Services.Mpris
import Quickshell.Services.SystemTray

ShellRoot {
  id: root

  // Whether the quick settings panel (QuickPanel.qml) is open.
  property bool panelOpen: false

  // Theme palette, generated by `omarchy-theme` (matugen) at
  // ~/.config/omarchy/colors.json. Falls back to Catppuccin Mocha if missing.
  readonly property var defaultTheme: ({
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    surface: "#313244",
    accent: "#89b4fa",
    error: "#f38ba8"
  })
  readonly property var theme: {
    const raw = themeFile.text();
    if (!raw)
      return root.defaultTheme;
    try {
      return Object.assign({}, root.defaultTheme, JSON.parse(raw));
    } catch (e) {
      return root.defaultTheme;
    }
  }

  FileView {
    id: themeFile
    path: (Quickshell.env("XDG_CONFIG_HOME") || (Quickshell.env("HOME") + "/.config")) + "/omarchy/colors.json"
    watchChanges: true
    onFileChanged: reload()
  }

  Variants {
    model: Quickshell.screens

    delegate: PanelWindow {
      id: bar
      required property var modelData

      screen: modelData

      anchors {
        top: true
        left: true
        right: true
      }

      implicitHeight: 34
      exclusiveZone: 34
      color: bar.bg

      readonly property color fg: root.theme.foreground
      readonly property color accent: root.theme.accent
      readonly property color bg: root.theme.background
      readonly property color surface: root.theme.surface
      readonly property string barMonitor: bar.modelData ? bar.modelData.name : ""

      // Current MPRIS player: prefer a playing one, else the first available.
      readonly property var player: {
        const players = Mpris.players.values;
        for (const p of players)
          if (p.isPlaying)
            return p;
        return players.length > 0 ? players[0] : null;
      }
      readonly property string mediaLabel: bar.player
        ? ((bar.player.trackArtist ? bar.player.trackArtist + " — " : "")
          + (bar.player.trackTitle ? bar.player.trackTitle : "Unknown"))
        : ""

      // Workspaces (left) -------------------------------------------------
      Row {
        anchors.left: parent.left
        anchors.leftMargin: 12
        anchors.verticalCenter: parent.verticalCenter
        spacing: 6

        Repeater {
          model: Hyprland.workspaces

          delegate: Rectangle {
            id: wsPill
            required property var modelData

            visible: modelData.id > 0
              && modelData.monitor
              && modelData.monitor.name === bar.barMonitor

            width: 26
            height: 22
            radius: 6
            color: modelData.active ? bar.accent : "transparent"

            Text {
              anchors.centerIn: parent
              text: wsPill.modelData.name
              color: wsPill.modelData.active ? bar.bg : bar.fg
              font.pixelSize: 12
              font.family: "monospace"
            }

            MouseArea {
              anchors.fill: parent
              onClicked: Hyprland.dispatch("workspace " + wsPill.modelData.id)
            }
          }
        }
      }

      // Clock + now-playing (center) --------------------------------------
      property var now: new Date()

      Timer {
        interval: 1000
        running: true
        repeat: true
        onTriggered: bar.now = new Date()
      }

      // Now-playing: shown only while an MPRIS player exists; click to toggle.
      RowLayout {
        anchors.centerIn: parent
        spacing: 18

        Text {
          Layout.alignment: Qt.AlignVCenter
          visible: bar.player !== null
          text: bar.mediaLabel
          color: bar.fg
          font.pixelSize: 12
          font.family: "monospace"
          elide: Text.ElideRight
          width: Math.min(implicitWidth, 320)

          MouseArea {
            anchors.fill: parent
            onClicked: {
              if (bar.player !== null && bar.player.canTogglePlaying)
                bar.player.togglePlaying();
            }
          }
        }

        Text {
          Layout.alignment: Qt.AlignVCenter
          text: Qt.formatDateTime(bar.now, "dddd HH:mm")
          color: bar.fg
          font.pixelSize: 13
          font.family: "monospace"
        }
      }

      // Status (right) ----------------------------------------------------
      RowLayout {
        anchors.right: parent.right
        anchors.rightMargin: 12
        anchors.verticalCenter: parent.verticalCenter
        spacing: 12

        // Bluetooth
        Image {
          Layout.alignment: Qt.AlignVCenter
          visible: Bluetooth.defaultAdapter !== null
          source: Quickshell.iconPath("bluetooth", true)
          opacity: (Bluetooth.defaultAdapter !== null
            && Bluetooth.defaultAdapter.enabled) ? 1.0 : 0.4
          sourceSize.width: 16
          sourceSize.height: 16

          MouseArea {
            anchors.fill: parent
            onClicked: {
              if (Bluetooth.defaultAdapter !== null)
                Bluetooth.defaultAdapter.enabled = !Bluetooth.defaultAdapter.enabled;
            }
          }
        }

        // Network
        Image {
          Layout.alignment: Qt.AlignVCenter
          source: Quickshell.iconPath(Networking.wifiEnabled
            ? "network-wireless"
            : "network-wired", true)
          sourceSize.width: 16
          sourceSize.height: 16

          MouseArea {
            anchors.fill: parent
            onClicked: Networking.wifiEnabled = !Networking.wifiEnabled;
          }
        }

        // Audio
        Text {
          Layout.alignment: Qt.AlignVCenter
          color: bar.fg
          font.pixelSize: 13
          font.family: "monospace"
          text: {
            const sink = Pipewire.defaultAudioSink;
            if (!sink || !sink.audio)
              return "";
            if (sink.audio.muted)
              return "muted";
            return Math.round(sink.audio.volume * 100) + "%";
          }
        }

        // Battery
        Text {
          Layout.alignment: Qt.AlignVCenter
          color: bar.fg
          font.pixelSize: 13
          font.family: "monospace"
          visible: UPower.displayDevice !== null
            && UPower.displayDevice.isLaptopBattery
          text: (UPower.displayDevice !== null
            && UPower.displayDevice.ready)
            ? Math.round(UPower.displayDevice.percentage * 100) + "%"
            : ""
        }

        // System tray
        Row {
          Layout.alignment: Qt.AlignVCenter
          spacing: 6

          Repeater {
            model: SystemTray.items

            delegate: Image {
              required property var modelData

              source: Quickshell.iconPath(modelData.icon, true)
              sourceSize.width: 16
              sourceSize.height: 16

              MouseArea {
                anchors.fill: parent
                acceptedButtons: Qt.LeftButton | Qt.RightButton
                onClicked: function (mouse) {
                  if (mouse.button === Qt.LeftButton)
                    modelData.activate();
                  else if (modelData.hasMenu)
                    modelData.display(parent, mouse.x, mouse.y);
                }
              }
            }
          }
        }

        // Quick settings button: opens the aggregate panel below.
        Item {
          Layout.alignment: Qt.AlignVCenter
          width: 22
          height: 22

          Text {
            anchors.centerIn: parent
            text: "≡"
            color: root.panelOpen ? bar.accent : bar.fg
            font.pixelSize: 16
            font.family: "monospace"
          }

          MouseArea {
            anchors.fill: parent
            onClicked: root.panelOpen = !root.panelOpen
          }
        }
      }
    }
  }

  // Transparent full-screen catcher: click anywhere or press Escape to dismiss
  // the quick settings panel. Draws below the panel.
  Variants {
    model: Quickshell.screens

    delegate: PanelWindow {
      required property var modelData
      screen: modelData
      visible: root.panelOpen
      color: "transparent"
      anchors {
        top: true
        left: true
        right: true
        bottom: true
      }
      exclusionZone: 0
      exclusionMode: ExclusionMode.Ignore
      WlrLayershell.layer: WlrLayer.Overlay
      WlrLayershell.namespace: "quickshell:quickpanel-catcher"
      WlrLayershell.keyboardFocus: WlrKeyboardFocus.OnDemand

      MouseArea {
        anchors.fill: parent
        focus: true
        onClicked: root.panelOpen = false
        Keys.onEscapePressed: root.panelOpen = false
      }
    }
  }

  // The quick settings panel itself, drawn above the catcher.
  Variants {
    model: Quickshell.screens

    delegate: QuickPanel {
      theme: root.theme
      open: root.panelOpen
      onDismiss: root.panelOpen = false
    }
  }
}
