# Syncthing folder/device pool — the single source of truth for what every host
# syncs. Imported by services/syncthing/default.nix.
#
# The 34 folders + 9 devices below are the exact set exported from the live
# host (laptop-p16, CachyOS) at `~/.local/state/syncthing/config.xml`, plus the
# new laptop-xps device (whose cert was pre-generated). Every NixOS host built
# from this flake syncs all of these folders, replicating each to nestor and the
# two other laptops as the closest-to-backup copy.
#
# A host only needs to set `services.syncthing.self` to its device name; the
# module derives its folders/devices from this pool.

{
  # Every known device. `id` is the stable Syncthing device ID. The device
  # whose `name` equals `services.syncthing.self` is the local node; its cert/key
  # are auto-generated by the activation script (services/syncthing/default.nix).
  devices = {
    "laptop-p16" = {
      id = "VCAGGHS-UIB4JTB-7WKWTG5-UB2WNV5-NQLN6V2-7AP7LUE-EPH5C5Z-XT2ZSQB";
    };
    "laptop-hera" = {
      id = "6RRKHEE-MRIC72T-KDZH7MW-NTHI7GU-6AWIJE5-PLFCPNO-L3RCZVA-LNY6YAC";
    };
    "laptop-xps" = {
      # Pre-generated so the device ID is stable and known ahead of install.
      # The matching cert/key live in secrets/syncthing/laptop-xps/ (gitignored);
      # they are copied to /etc/nixos/secrets by the activation script.
      id = "MMPI6MM-BLZL6TA-QLI4BWG-33G77VU-RLAH2YQ-UEJV3EB-MENPSIZ-L3UCJQI";
    };
    "nestor" = {
      id = "X2BF7X6-AR33BUE-32MXKRW-VTRRVJM-53DNXSQ-AN26QLX-DOMXCFS-DYJU4Q3";
    };
    "phone-pixel3a" = {
      id = "CIHWVS6-UBZ2XDZ-FDMXIIX-PBNSW6V-UFG4WKQ-55WDKUZ-FWCL5B4-AT6U4A6";
    };
    "phone-OnePlusNord" = {
      id = "SF6S7D2-P2FKU3S-GQOLHEH-RMZECJM-NLK33TZ-FBJYMSC-HR3MDOE-U4CLTAF";
    };
    "phone-pixel8a" = {
      id = "SLSV3BR-WNREAHF-7Q4ZSI7-ZKQVEW7-FFM5UJX-WVUCEKO-KGXZOFO-SNL6WAH";
    };
    "phone-pixel6a" = {
      id = "YJF7LAI-FVVUWAU-Q4BFON6-V2376XX-FBR67Y2-2HM5YHY-JMZRVFB-2G7YEAJ";
    };
    "hassio" = {
      id = "HOYGZXB-5US6BPN-OZ6TLD7-F4FAUT6-XB557PL-U5EY46K-NIR7AFH-PAWWEAZ";
    };
  };

  # All 34 folders. Keyed by their stable folder ID (must match across devices).
  # `devices` lists the peer device names sharing this folder. The module
  # enables a folder on a host iff `self` is in its device list, and declares
  # that folder as shared with exactly those peers.
  #
  # path = /sync/<label> on every NixOS host. All are sendreceive with
  # staggered versioning (maxAge 1y) and a 1h rescan — matching the live host.
  folders = {
    "00-09 - Management and Meta" = {
      id = "k7t9g-2y5as";
      devices = [ "hassio" "phone-OnePlusNord" "phone-pixel8a" "laptop-p16" "nestor" "phone-pixel6a" "laptop-hera" "laptop-xps" ];
    };
    "10-19 - Personnes et Animaux" = {
      id = "pz9yw-7sppl";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "20-29 - Secrets" = {
      id = "jhrug-pluzk";
      devices = [ "phone-OnePlusNord" "phone-pixel8a" "laptop-p16" "nestor" "phone-pixel6a" "laptop-hera" "laptop-xps" ];
    };
    "30-39 - Formation développement loisirs" = {
      id = "wrgy5-cfk7s";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "40-49 - Backups" = {
      id = "darda-brujx";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "50-59 - Finance et Assurance" = {
      id = "t6swq-u9tu6";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "70-79 - Administration et Etat" = {
      id = "szjwp-hkq4t";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "80-89 - Actifs" = {
      id = "tkqxb-9fp6t";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "90-99 - Public stuff" = {
      id = "dxjen-ryhzq";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Android Camera" = {
      id = "pixel_8a_ruqh-photos";
      devices = [ "phone-pixel8a" "laptop-p16" "nestor" "phone-pixel6a" "laptop-hera" "laptop-xps" ];
    };
    "Calibre Library" = {
      id = "uefut-5awdq";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Camera Pixel3a" = {
      id = "apn3p-rscuc";
      devices = [ "phone-pixel3a" "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Camera Pixel6a" = {
      id = "pixel_6a_71kh-photos";
      devices = [ "laptop-p16" "nestor" "phone-pixel6a" "laptop-hera" "laptop-xps" ];
    };
    "Camera Uploads Christine" = {
      id = "fsfij-7rnlh";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Camera Uploads Christine oneplusnord" = {
      id = "ac2003_b8vg-photos";
      devices = [ "phone-OnePlusNord" "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Camera phone-pixel3a" = {
      id = "pixel_3a_4s5y-photos";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Dictaphone" = {
      id = "602jh-lb39h";
      devices = [ "laptop-p16" "nestor" "phone-pixel6a" "laptop-hera" "laptop-xps" ];
    };
    "FileDrop" = {
      id = "hgetx-7cc6x";
      devices = [ "phone-pixel3a" "phone-OnePlusNord" "phone-pixel8a" "laptop-p16" "nestor" "phone-pixel6a" "laptop-hera" "laptop-xps" ];
    };
    "FileDropRandstadDigital" = {
      id = "nffhs-npqjb";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Photos" = {
      id = "nu5c3-ryptx";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Pixel6a Videos" = {
      id = "tn1rb-v20lm";
      devices = [ "laptop-p16" "nestor" "phone-pixel6a" "laptop-hera" "laptop-xps" ];
    };
    "Scans" = {
      id = "vxuuw-zcf7m";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "Zotero" = {
      id = "ddg7b-dtlhb";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "christine" = {
      id = "4wsaa-aspyf";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "christine-dot-mozilla" = {
      id = "k26ga-rhpeq";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "code" = {
      id = "b7vv2-aomur";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "code_rd" = {
      id = "lou4f-crany";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "encrypted_password" = {
      id = "vx54o-nc963";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "hassioconfig" = {
      id = "aabts-zpssr";
      devices = [ "hassio" "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "music" = {
      id = "xkfuh-ep2th";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "nixos" = {
      id = "yojhk-vh7km";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "notes" = {
      id = "kjauq-uhiyv";
      devices = [ "phone-OnePlusNord" "phone-pixel8a" "laptop-p16" "nestor" "phone-pixel6a" "laptop-hera" "laptop-xps" ];
    };
    "software" = {
      id = "haoqu-jdh4f";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
    "yannick" = {
      id = "pjpya-zmdwj";
      devices = [ "laptop-p16" "nestor" "laptop-hera" "laptop-xps" ];
    };
  };
}
