{ config, lib, pkgs, ... }:

with lib;
{
  environment.systemPackages = with pkgs; [
    virt-manager-qt # Desktop user interface for managing virtual machines (QT)
  ];
  programs = {
    virt-manager = {
      enable = true; # Whether to enable virt-manager, an UI for managing virtual machines in libvirt.
    };
  };
  virtualisation = {
    libvirtd = {
      enable = true; # This option enables libvirtd, a daemon that manages virtual machines. Users in the “libvirtd” group can interact with the daemon (e.g. to start or stop VMs) using the virsh command line tool, among others.
    };
    spiceUSBRedirection.enable = true;
    kvmgt = { # https://nixos.wiki/wiki/IGVT-g: Intel GVT-g is a technology that allows to "slice" an Intel GPU into virtualized GPUs that can be then passed into virtual machines. 
      enable = true; # Whether to enable KVMGT (iGVT-g) VGPU support. Allows Qemu/KVM guests to share host’s Intel integrated graphics card. Currently only one graphical device can be shared. To allow users to access the device without root add them to the kvm group.
      # Option "vgpus" is commented out, as else the resolution of any secondary monitor will be limited to that of the vgpu (1024x768...)
      # vgpus = (if (config.networking.hostName == "laptop-xps") then 
      #   {
      #     "i915-GVTg_V5_4" = {
      #       uuid = [ "660a3c9f-18f8-48be-b850-e44d545d41a1" ]; # this UUID has been generated by us and may be used inside a KVM/libvirt VM config to reference the virtual GPU
      #     };
      #     # only one virtual GPU is allowed, so we disable this one.
      #     /* "i915-GVTg_V5_8" = {
      #       uuid = [ "5f30d0c1-dacb-4f5c-97c4-adf9fe7a41c7" ];
      #     }; */ 
      #   }
      # else 
      #   {}
      # );
    };
  };
}
